import { Ionicons } from '@expo/vector-icons';
import { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { AdminActionMenu } from './admin-action-menu';

const N='#061F68', B='#1268E8', G='#079455';
const seed=[
 ['05/09/2026 09:14','Versement','Nouveau versement reçu','Versement de 120 000 CDF via M-Pesa pour Jean Mukendi.','Jean Mukendi','Non lue','TRX893745'],
 ['05/09/2026 08:52','Inscription','Nouveau chauffeur inscrit','Patrick Lemba a soumis une demande d’inscription.','Patrick Lemba','Non lue','USR9821'],
 ['04/09/2026 18:32','Agence','Demande de validation','Trans-Academia a soumis ses documents pour validation.','Trans-Academia','Non lue','AGE7821'],
 ['04/09/2026 14:20','Réclamation','Nouvelle réclamation','Problème de paiement signalé par un client.','Client','Non lue','REC5432'],
 ['03/09/2026 16:11','Carte NFC','Carte NFC activée','Carte NFC #TKC45879 activée avec succès.','David Nsele','Lue','TKC45879'],
 ['03/09/2026 11:05','Paiement','Échec de paiement','Tentative de paiement échouée : fonds insuffisants.','Client','Lue','PAY7712'],
 ['02/09/2026 19:47','Trésorerie','Solde faible','Le solde Orange Money est inférieur au seuil défini.','Système','Lue','ALT8920'],
 ['02/09/2026 13:18','Billetterie','Nouvelle réservation','Réservation Kinshasa – Matadi pour 2 passagers.','Client','Lue','BIL7812'],
] as const;
export function AdminNotifications(){const [items,setItems]=useState(seed.map((x,i)=>({x:[...x],id:i})));const [query,setQuery]=useState('');const [type,setType]=useState('Tous les types');const [status,setStatus]=useState('Toutes');const [selected,setSelected]=useState(items[0]);const rows=useMemo(()=>items.filter(({x})=>x.join(' ').toLowerCase().includes(query.toLowerCase())&&(type==='Tous les types'||x[1]===type)&&(status==='Toutes'||x[5]===status)),[items,query,type,status]);const unread=items.filter(({x})=>x[5]==='Non lue').length;const mark=(id:number)=>setItems(v=>v.map(o=>o.id===id?{...o,x:o.x.map((z,i)=>i===5?'Lue':z)}:o));return <View style={s.page}>
 <View style={s.top}><TouchableOpacity style={s.secondary} onPress={()=>setItems(v=>v.map(o=>({...o,x:o.x.map((z,i)=>i===5?'Lue':z)})))}><Ionicons name="checkmark" size={17} color={N}/><Text style={s.secondaryText}>Marquer tout comme lu</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>Alert.alert('Paramètres','Les préférences de notifications sont prêtes à être configurées.')}><Ionicons name="settings-outline" size={17} color={N}/><Text style={s.secondaryText}>Paramètres de notifications</Text></TouchableOpacity></View>
 <View style={s.metrics}><Metric icon="notifications-outline" label="Total notifications" value={items.length} color="#E97912" hint="Ce mois-ci"/><Metric icon="ellipse" label="Non lues" value={unread} color={B} hint="À traiter"/><Metric icon="checkmark-circle-outline" label="Lues" value={items.length-unread} color={G} hint="Déjà consultées"/><Metric icon="alert-circle" label="Urgentes" value="3" color="#D92D20" hint="Action requise"/></View>
 <View style={s.filters}><View style={s.search}><Ionicons name="search-outline" size={17} color="#667085"/><TextInput value={query} onChangeText={setQuery} placeholder="Rechercher une notification…" style={s.input}/></View><Picker value={type} values={['Tous les types','Versement','Inscription','Agence','Réclamation','Carte NFC','Paiement','Trésorerie','Billetterie']} set={setType}/><Picker value={status} values={['Toutes','Non lue','Lue']} set={setStatus}/><TouchableOpacity style={s.primary} onPress={()=>{setQuery('');setType('Tous les types');setStatus('Toutes')}}><Ionicons name="refresh-outline" size={17} color="white"/><Text style={s.primaryText}>Actualiser</Text></TouchableOpacity></View>
 <View style={s.layout}><View style={s.tableCard}><Text style={s.title}>Liste des notifications</Text><View style={[s.row,s.head]}>{['Date & heure','Type','Titre','Message','Utilisateur concerné','Statut','Actions'].map(h=><Text key={h} style={[s.th,h==='Actions'&&s.center]}>{h}</Text>)}</View>{rows.map(o=>{const x=o.x;return <TouchableOpacity key={o.id} style={[s.row,x[5]==='Non lue'&&s.unread]} onPress={()=>setSelected(o)}><Text style={s.cell}>{x[0]}</Text><Text style={[s.cell,s.type]}>{x[1]}</Text><Text style={s.strong}>{x[2]}</Text><Text style={s.cell}>{x[3]}</Text><Text style={s.cell}>{x[4]}</Text><Text style={[s.cell,x[5]==='Non lue'?s.new:s.read]}>● {x[5]}</Text><View style={[s.cell,s.centerCell]}><AdminActionMenu actions={[{label:'Voir les détails',icon:'eye-outline',onPress:()=>setSelected(o)},{label:'Marquer comme lu',icon:'checkmark-outline',onPress:()=>mark(o.id),disabled:x[5]==='Lue'},{label:'Supprimer',icon:'trash-outline',danger:true,onPress:()=>setItems(v=>v.filter(a=>a.id!==o.id))}]} /></View></TouchableOpacity>})}<View style={s.footer}><Text style={s.muted}>Affichage de 1 à {rows.length} sur {items.length} notifications</Text><Text style={s.pageNo}>1</Text></View></View>
 <View style={s.side}><View style={s.card}><Text style={s.title}>Détails de la notification</Text>{selected?<><Text style={s.detailTitle}>{selected.x[2]}</Text><Text style={s.muted}>{selected.x[0]} · {selected.x[1]}</Text><Text style={s.message}>{selected.x[3]}</Text><Detail l="Utilisateur" v={selected.x[4]}/><Detail l="Référence" v={selected.x[6]}/><Detail l="Statut" v={selected.x[5]}/><TouchableOpacity style={s.primary} onPress={()=>Alert.alert('Transaction',selected.x[6])}><Ionicons name="open-outline" size={17} color="white"/><Text style={s.primaryText}>Voir la transaction</Text></TouchableOpacity></>:null}</View><View style={s.card}><Text style={s.title}>Paramètres des notifications</Text><Text style={s.message}>Configurez les types de notifications que vous souhaitez recevoir.</Text><TouchableOpacity style={s.secondary}><Ionicons name="options-outline" size={17} color={N}/><Text style={s.secondaryText}>Modifier les préférences</Text></TouchableOpacity></View></View></View>
 </View>}
function Metric({icon,label,value,color,hint}:any){return <View style={s.metric}><View style={[s.metricIcon,{backgroundColor:`${color}16`}]}><Ionicons name={icon} size={24} color={color}/></View><View><Text style={s.muted}>{label}</Text><Text style={s.metricValue}>{value}</Text><Text style={s.muted}>{hint}</Text></View></View>};function Picker({value,values,set}:any){return <TouchableOpacity style={s.picker} onPress={()=>set(values[(values.indexOf(value)+1)%values.length])}><Text style={s.pickerText}>{value}</Text><Ionicons name="chevron-down" size={15} color={N}/></TouchableOpacity>};function Detail({l,v}:any){return <View style={s.detail}><Text style={s.muted}>{l}</Text><Text style={s.strong}>{v}</Text></View>}
const s=StyleSheet.create({page:{gap:13},top:{flexDirection:'row',justifyContent:'flex-end',gap:9},primary:{minHeight:38,borderRadius:6,backgroundColor:B,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'white',fontSize:10,fontWeight:'700'},secondary:{minHeight:38,borderWidth:1,borderColor:'#D7DFEA',borderRadius:6,paddingHorizontal:13,backgroundColor:'white',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},secondaryText:{color:N,fontSize:10,fontWeight:'600'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:12},metric:{flex:1,minWidth:200,minHeight:90,borderWidth:1,borderColor:'#E4EAF2',borderRadius:9,backgroundColor:'white',padding:14,flexDirection:'row',alignItems:'center',gap:11},metricIcon:{width:43,height:43,borderRadius:9,alignItems:'center',justifyContent:'center'},metricValue:{color:N,fontSize:20,fontWeight:'800',marginVertical:2},filters:{padding:12,borderWidth:1,borderColor:'#E4EAF2',borderRadius:9,backgroundColor:'white',flexDirection:'row',flexWrap:'wrap',gap:10},search:{flex:1,minWidth:230,height:39,borderWidth:1,borderColor:'#D7DFEA',borderRadius:6,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:7},input:{flex:1,fontSize:10,color:N,outlineStyle:'none'} as any,picker:{minWidth:180,height:39,borderWidth:1,borderColor:'#D7DFEA',borderRadius:6,paddingHorizontal:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},pickerText:{color:N,fontSize:10},layout:{flexDirection:'row',alignItems:'flex-start',gap:12},tableCard:{flex:1,minWidth:0,borderWidth:1,borderColor:'#E4EAF2',borderRadius:9,backgroundColor:'white',padding:12},title:{color:N,fontSize:14,fontWeight:'800',marginBottom:10},row:{minWidth:850,minHeight:54,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#EEF2F6',gap:7},head:{minHeight:36},th:{flex:1,color:'#344054',fontSize:8,fontWeight:'700'},cell:{flex:1,color:'#475467',fontSize:9},strong:{flex:1,color:N,fontSize:9,fontWeight:'700'},center:{textAlign:'center'},centerCell:{alignItems:'center'},unread:{backgroundColor:'#F1F7FF'},type:{color:B,fontWeight:'700'},new:{color:B,fontWeight:'700'},read:{color:G,fontWeight:'700'},footer:{height:43,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},muted:{color:'#667085',fontSize:9,marginTop:2},pageNo:{color:'white',backgroundColor:B,paddingHorizontal:11,paddingVertical:7,borderRadius:5,fontSize:10},side:{width:275,gap:12},card:{borderWidth:1,borderColor:'#E4EAF2',borderRadius:9,backgroundColor:'white',padding:14,gap:9},detailTitle:{color:N,fontSize:13,fontWeight:'800'},message:{color:'#475467',fontSize:10,lineHeight:16},detail:{minHeight:35,borderTopWidth:1,borderTopColor:'#EEF2F6',flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8}});
