import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { Alert, Text, TouchableOpacity, View, StyleSheet } from 'react-native';
import QRCode from 'react-native-qrcode-svg';

const NAVY = '#07183F';
const BLUE = '#1264ED';
const GREEN = '#079455';

function CardTitle({ icon, children }: { icon: keyof typeof Ionicons.glyphMap; children: string }) {
  return <View style={s.cardTitle}><Ionicons name={icon} size={20} color={BLUE} /><Text style={s.cardTitleText}>{children}</Text></View>;
}

function InfoRow({ icon, label, value, badge }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; badge?: boolean }) {
  return <View style={s.infoRow}><Ionicons name={icon} size={17} color={NAVY} /><Text style={s.infoLabel}>{label}</Text><Text style={[s.infoValue, badge && s.badge]}>{value}</Text></View>;
}

export function DriverProfile({ user, driverTripInfo, onEdit }: { user: any; driverTripInfo: any; onEdit: () => void }) {
  const name = user?.fullName || 'Partenaire TaKo';
  const driverCode = String(user?.id || user?.email || name);
  const joined = user?.createdAt ? new Date(user.createdAt).toLocaleDateString('fr-FR', { day:'numeric', month:'long', year:'numeric' }) : '5 septembre 2026';
  return <View style={s.page}>
    <View style={s.heading}><View><Text style={s.title}>Mon profil</Text><Text style={s.subtitle}>Consultez et gérez vos informations personnelles</Text></View><TouchableOpacity style={s.editButton} onPress={onEdit}><Ionicons name="create-outline" size={17} color="white" /><Text style={s.editText}>Modifier le profil</Text></TouchableOpacity></View>
    <View style={s.identityCard}><View style={s.avatar}><Ionicons name="person" size={60} color={BLUE} /><View style={s.camera}><Ionicons name="camera" size={15} color="white" /></View></View><View style={s.identity}><Text style={s.name}>{name}</Text><View style={s.role}><MaterialCommunityIcons name="bus" size={15} color={BLUE} /><Text style={s.roleText}>Partenaire</Text></View><Text style={s.verified}>● Compte vérifié</Text><Text style={s.subtitle}>Votre compte est actif et prêt à l’utilisation.</Text></View><View style={s.qr}><QRCode value={driverCode} size={88} /><Text style={s.qrTitle}>Mon code partenaire</Text><Text style={s.qrHint}>Présentez ce QR code si nécessaire</Text></View></View>
    <View style={s.columns}><View style={s.left}>
      <View style={s.card}><CardTitle icon="person-outline">Informations personnelles</CardTitle><InfoRow icon="person-outline" label="Nom complet" value={name} /><InfoRow icon="call-outline" label="Numéro de téléphone" value={user?.phone || 'Non renseigné'} /><InfoRow icon="mail-outline" label="Adresse e-mail" value={user?.email || 'Non renseignée'} /><InfoRow icon="calendar-outline" label="Date de naissance" value={user?.birthDate || 'Non renseignée'} /><InfoRow icon="location-outline" label="Adresse" value={user?.address || 'Kinshasa, RDC'} /><InfoRow icon="document-text-outline" label="Numéro de pièce d’identité" value={user?.identityNumber || 'Non renseigné'} /><InfoRow icon="calendar-outline" label="Date d’expiration" value={user?.identityExpiry || 'Non renseignée'} /></View>
      <View style={[s.card,s.password]}><CardTitle icon="lock-closed">Changer mon mot de passe</CardTitle><Text style={s.passwordText}>Pour plus de sécurité, changez régulièrement votre mot de passe.</Text><TouchableOpacity style={s.softButton} onPress={() => Alert.alert('Mot de passe','La modification sécurisée du mot de passe est prête.')}><Ionicons name="key-outline" size={16} color={BLUE} /><Text style={s.softText}>Changer le mot de passe</Text></TouchableOpacity></View>
    </View><View style={s.right}>
      <View style={s.card}><CardTitle icon="people-outline">Informations de compte</CardTitle><InfoRow icon="people-outline" label="Rôle" value="Partenaire" /><InfoRow icon="person-outline" label="Statut du compte" value="Actif" badge /><InfoRow icon="calendar-outline" label="Date d’inscription" value={joined} /><InfoRow icon="time-outline" label="Dernière connexion" value={new Date().toLocaleString('fr-FR')} /><InfoRow icon="shield-checkmark-outline" label="Vérification" value="Compte vérifié" badge /></View>
      <View style={s.card}><CardTitle icon="bus-outline">Mon véhicule</CardTitle><InfoRow icon="bus-outline" label="Véhicule TaKo" value={driverTripInfo?.bus || 'Ligne non renseignée'} /><InfoRow icon="card-outline" label="Plaque d’immatriculation" value={driverTripInfo?.busPlate || 'Non renseignée'} /><InfoRow icon="map-outline" label="Ligne(s) desservie(s)" value={driverTripInfo?.route || 'Non renseignée'} /><InfoRow icon="sync-outline" label="Statut du véhicule" value="Véhicule vérifié" badge /><TouchableOpacity style={s.vehicleButton} onPress={onEdit}><Ionicons name="create-outline" size={16} color={BLUE} /><Text style={s.softText}>Modifier les informations du véhicule</Text></TouchableOpacity></View>
    </View></View>
  </View>;
}

const s = StyleSheet.create({page:{gap:14},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:22,fontWeight:'900',color:NAVY},subtitle:{fontSize:12,color:'#667085',marginTop:4},editButton:{height:40,borderRadius:7,backgroundColor:BLUE,paddingHorizontal:17,flexDirection:'row',alignItems:'center',gap:7},editText:{color:'white',fontSize:11,fontWeight:'700'},identityCard:{minHeight:170,borderWidth:1,borderColor:'#E3E8F0',borderRadius:10,backgroundColor:'white',padding:20,flexDirection:'row',alignItems:'center'},avatar:{width:120,height:120,borderRadius:60,backgroundColor:'#E8EEF8',alignItems:'center',justifyContent:'center',position:'relative'},camera:{position:'absolute',right:1,bottom:8,width:31,height:31,borderRadius:16,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},identity:{flex:1,paddingLeft:34},name:{fontSize:19,fontWeight:'900',color:NAVY},role:{marginTop:9,alignSelf:'flex-start',flexDirection:'row',gap:6,backgroundColor:'#EEF2FF',paddingHorizontal:10,paddingVertical:6,borderRadius:5},roleText:{fontSize:11,fontWeight:'700',color:BLUE},verified:{color:GREEN,fontSize:11,fontWeight:'800',marginTop:14},qr:{width:250,borderLeftWidth:1,borderLeftColor:'#EEF2F6',alignItems:'center'},qrTitle:{fontSize:10,fontWeight:'800',color:NAVY,marginTop:7},qrHint:{fontSize:9,color:'#667085',marginTop:3},columns:{flexDirection:'row',gap:14},left:{flex:1,gap:14},right:{flex:1,gap:14},card:{backgroundColor:'white',borderWidth:1,borderColor:'#E3E8F0',borderRadius:10,padding:16},cardTitle:{height:31,flexDirection:'row',alignItems:'flex-start',gap:9},cardTitleText:{fontSize:14,fontWeight:'900',color:NAVY},infoRow:{minHeight:37,borderBottomWidth:1,borderBottomColor:'#EEF2F6',flexDirection:'row',alignItems:'center',gap:9},infoLabel:{width:180,fontSize:10,color:'#526078'},infoValue:{flex:1,fontSize:10,color:NAVY,fontWeight:'600'},badge:{flex:0,backgroundColor:'#DCFCE7',color:GREEN,paddingHorizontal:9,paddingVertical:5,borderRadius:5,overflow:'hidden',fontWeight:'800'},password:{minHeight:105,position:'relative'},passwordText:{fontSize:10,color:'#667085',marginLeft:29,maxWidth:260,lineHeight:15},softButton:{position:'absolute',right:14,bottom:23,minHeight:36,paddingHorizontal:13,borderRadius:5,backgroundColor:'#EAF1FF',flexDirection:'row',alignItems:'center',gap:6},softText:{fontSize:10,fontWeight:'700',color:BLUE},vehicleButton:{height:38,marginTop:12,borderRadius:5,backgroundColor:'#EAF1FF',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7}});
